cmake_minimum_required(VERSION 3.16)
project(ur3_offline_collision LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
find_package(ament_cmake REQUIRED)
find_package(moveit_core REQUIRED)
find_package(urdf REQUIRED)
find_package(srdfdom REQUIRED)
find_package(yaml-cpp REQUIRED)
find_package(joint_trajectory_controller REQUIRED)
add_executable(check_self_collision check_self_collision.cpp)
ament_target_dependencies(check_self_collision moveit_core urdf srdfdom)
target_link_libraries(check_self_collision yaml-cpp)
add_executable(sample_timed_trajectory sample_timed_trajectory.cpp)
ament_target_dependencies(sample_timed_trajectory joint_trajectory_controller)
target_link_libraries(sample_timed_trajectory yaml-cpp)
