# Installed for Universal Robots ROS 2 driver real-time scheduling.
@realtime soft rtprio 99
@realtime hard rtprio 99
@realtime soft priority 99
@realtime hard priority 99
@realtime soft memlock 102400
@realtime hard memlock 102400
